### ISSUE TITLE
Releasing OMS

### ISSUE THREAD

**Issue by judepereira** [microservices/oms#298]
## Goal:
Have the validation endpoint use the new OMS tool (uses the OMS validation package from npm)

### TODOs
- [x] Merge the rebranding from OMG to OMS branch into new dawn - @StoryscriptHuman 
- [x] Back port features/fixes from master into the new dawn branch - @StoryscriptHuman 
- [x] Get regression testing working for the CLI - @judepereira 
- [x] Add --experimental flag to the UI command (print if flag is missing) - @StoryscriptHuman 
- [x] Test validation package with well known, good services - @judepereira 
- [x] Replace master with new dawn 
- [x] Update Docker Hub image for the validation endpoint
  - [x] Republish, since it's under Aurelien's name? (see https://github.com/microservices/microservice-validate/pull/3)
  - [x] Merge `@microservices/validates` package update (see https://github.com/oms-services/oms-validate/pull/4)
- [x] Update the stories app to use the newly published validation service
- [x] Update CLI documentation on openmicroservices.org (e.g. https://github.com/microservices/openmicroservices.org/issues/155) - @matthewhudson 
- [x] Update Mailgun templates to OMS
  - [x] Merge `hub-api` PR: https://github.com/storyscript/hub-api/pull/52
  - [x] [followup] Delete legacy OMG templates from Mailgun interface 
- [ ] [optional] Release openapi2oms on PyPI (see https://github.com/microservices/openapi2oms/issues/7)
